### ISSUE TITLE
Pixelated stack glow

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#588]
Champ99 reports the stack-running highlight/glow is showing up pixelated on her MacBook. Screenshot forthcoming.

**Comment by rachel-fenichel** [comment]
Also on my x1 carbon:
![image](https://cloud.githubusercontent.com/assets/13686399/18291292/e34e4c6c-743b-11e6-93a3-43fb44cfadf0.png)

**Comment by rachel-fenichel** [comment]
And the problem goes away if I zoom in, with the blockly controls or by zooming the whole page with chrome:
![image](https://cloud.githubusercontent.com/assets/13686399/18291310/067dc3b6-743c-11e6-8369-17ab0e2a0311.png)

**Comment by tmickel** [comment]
Yep, and here's Champ's Macbook:
![image](https://cloud.githubusercontent.com/assets/120403/18315349/a453a328-74e4-11e6-824a-1612567d5c09.png)

Rachel is there any chance you can try tweaking the width sometime: https://github.com/LLK/scratch-blocks/blob/develop/core/inject.js#L43 since you have a readily accessible reproduction?

**Comment by tmickel** [comment]
I'm going to assign you with high hopes :P

**Comment by rachel-fenichel** [comment]
Screenshots for days!

Glow size 1, neutral zoom (I clicked the "center" button)
![image](https://cloud.githubusercontent.com/assets/13686399/18326869/a5ad8dca-74fc-11e6-9f5f-6949cc812082.png)

Glow size 1, zoomed out once
![image](https://cloud.githubusercontent.com/assets/13686399/18326856/958b3db6-74fc-11e6-9ff1-b6898d17061e.png)

Glow size 1, zoomed out twice
![image](https://cloud.githubusercontent.com/assets/13686399/18326814/817c7be6-74fc-11e6-81f6-511a9007fe83.png)

Glow size 2, neutral zoom
![image](https://cloud.githubusercontent.com/assets/13686399/18326889/bb95993e-74fc-11e6-99b9-8c9ec1cc27b3.png)

Glow size 2, zoomed out once
![image](https://cloud.githubusercontent.com/assets/13686399/18326884/b482b1e0-74fc-11e6-9e5b-23d0ac17a5e0.png)

Glow size 2, zoomed out twice
![image](https://cloud.githubusercontent.com/assets/13686399/18326873/ac2073a2-74fc-11e6-9337-5838b4d27087.png)

**Comment by tmickel** [comment]
@carljbowman Thoughts on glow size 2?

**Comment by tmickel** [comment]
Thanks Rachel!

**Comment by carljbowman** [comment]
@rachel-fenichel - Thanks for looking into this! The Glow size 2 looks good to me. 

The 'glow' renders pretty unpredictably across screen DPIs and variability of Zooming this effect proportionally creates more opportunities for aliasing. Within Scratch 2.0 the 'glow' appears to be set to a fixed size. Not only would a fixed 'glow' size limit the potential for aliasing, it also helps identify which stacks of blocks are running even when zoomed out.

@tmickel @rachel-fenichel - Thoughts?

**Comment by tmickel** [comment]
@carljbowman Aah, that makes a lot of sense. Should it be fixed to size 2?

**Comment by tmickel** [comment]
Or size 1? Because "Glow size 1, neutral zoom" (which presumably is how we would scale the glow to if "fixed") looked fine in Rachel's screenshot.

**Comment by carljbowman** [comment]
@tmickel - Depending on how difficult it is to make the glow size fixed, I am thinking we should just grab some devices and try it. Too many inconsistencies at play.

**Comment by tmickel** [comment]
Btw, @rachel-fenichel @ChampikaF we are hoping this problem has been solved by #615. If you ever get a chance to check it out, let us know!

**Comment by rachel-fenichel** [comment]
Is #615 live on the scratch-vm demo?

**Comment by tmickel** [comment]
There is no live scratch-vm demo :P

**Comment by towerofnix** [comment]
Are you sure? :shipit:

**Comment by ChampikaF** [comment]
I'm still seeing this on my demo for neutral zoom:

![image](https://cloud.githubusercontent.com/assets/2895591/18723707/949b9c14-7fee-11e6-925a-0cb8c376abf9.png)

**Comment by as-com** [comment]
@rachel-fenichel It should be live on my demo, if that's what you're talking about: https://utils.asun.co/scratch-vm/playground/

**Comment by tmickel** [comment]
@as-com It's not, since this hasn't been put into the compiled version

**Comment by as-com** [comment]
@tmickel I recompile scratch-blocks manually every time I update it from GitHub, so what's on my site should reflect what you have done so far.

**Comment by tmickel** [comment]
@as-com Nonetheless your copy doesn't reflect this change :P

**Comment by ChampikaF** [comment]
@tmickel here are screenshots from my machine - looking a lot better I think. 

Neutral zoom
![image](https://cloud.githubusercontent.com/assets/2895591/18880630/66bebb2a-848d-11e6-9525-5c8cf14f2599.png)

Zoomed out 1
![image](https://cloud.githubusercontent.com/assets/2895591/18880649/7a0f8cae-848d-11e6-9b08-8fd908f9dac0.png)

Zoomed in 1
![image](https://cloud.githubusercontent.com/assets/2895591/18880664/85c1d5ca-848d-11e6-90bf-6a741b0ea800.png)

Zoomed in 2
![image](https://cloud.githubusercontent.com/assets/2895591/18880685/9968e82a-848d-11e6-937c-91670ffef97b.png)

**Comment by tmickel** [comment]
Hmm, cool, thanks! Yeah I see the bit of problem on the rounded edges...not sure if that's resolvable though...

**Comment by ChampikaF** [comment]
Not sure if the thinner highlight is as easy to discern from non-highlighted state though..

**Comment by tmickel** [comment]
@carljbowman Thoughts?

**Comment by carljbowman** [comment]
@tmickel @ChampikaF - I agree, regardless of screen resolution, we should increase the glow size. 
As we move towards a 'light-mode' UI for the initial prototype we will also need to adjust the colors.

**Comment by tmickel** [comment]
Ok, I've bumped it up to 1.3. Worth testing again sometime :)

**Comment by tmickel** [comment]
Have heard that this is fixed.
