### ISSUE TITLE
npm install (windows)

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-blocks#833]
I fave a fork of the scratch blocks so I could develop it in conjunction with scratch gui, but npm install and npm link are both failing on the scratch blocks fork for me?

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-blocks@0.1.0 prepublish script 'python build.py && webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

Do I need to install python or perhaps the install does not work in windows?

Thank you

**Comment by rschamp** [comment]
@griffpatch Would you please post your `npm-debug.log`?  You do need Python installed, so also curious what happens with `python -V`.

**Comment by griffpatch** [comment]
Here's my log: [npm-debug.log.txt](https://github.com/LLK/scratch-blocks/files/836118/npm-debug.log.txt)

Hope that helps :) - Just to let you know I do now have Python installed and I can run python from the command prompt by typing "python" after I got the paths set up...

**Comment by griffpatch** [comment]
Just ran python on it's own with one of your .py scripts and note that I have python 3.x not 2.x...  I'll install version 2 instead, but it might be the console I'm running the scripts in that's the issue...?

**Comment by griffpatch** [comment]
Yeah, python 2 did the same... It doesn't appear to like the "`&&`" in "`python build.py && webpack`" ?
although I also don't like the:
```
93 warn optional Skipping failed optional dependency /chokidar/fsevents:
94 warn notsup Not compatible with your operating system or architecture: fsevents@1.1.1
```

This is now python 2.7.13 and it gets to the same place:

```
35285 verbose stack Error: scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
35285 verbose stack Exit status 1
35285 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
35285 verbose stack     at emitTwo (events.js:106:13)
35285 verbose stack     at EventEmitter.emit (events.js:191:7)
35285 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
35285 verbose stack     at emitTwo (events.js:106:13)
35285 verbose stack     at ChildProcess.emit (events.js:191:7)
35285 verbose stack     at maybeClose (internal/child_process.js:877:16)
35285 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
35286 verbose pkgid scratch-blocks@0.1.0
```

**Comment by rschamp** [comment]
@griffpatch It appears that the `install` part did complete successfully, so npm was attempting to do the post-install steps. This includes running `prepublish` if it exists.  The `&&` there should not be evaluated directly by Windows, since `npm` passes that through an intermediate process which parses it.  So I'm curious what happens if you run these commands individually? If you run `python build.py` what happens? And if that succeeds, `node_modules/.bin/webpack`?

**Comment by griffpatch** [comment]
This is what I get when running the python build.py:
```
~\Documents\GitHub\scratch-blocks [develop ≡]> python -V
Python 2.7.13
~\Documents\GitHub\scratch-blocks [develop ≡]> python build.py
Error: Closure not found.  Read this:
developers.google.com/blockly/guides/modify/web/closure
```

**Comment by rschamp** [comment]
Aha — on https://github.com/LLK/scratch-blocks/wiki we describe setting up a symlink from `../closure-library` to `./node_modules/google-closure-library`. This will make closure-library available from the directory above your scratch-blocks directory, which is where the build script looks for it. I believe the syntax for Windows would be `mklink /D ..\closure-library node_modules\google-closure-library`, but you probably know better on how to accomplish this.

**Comment by rachel-fenichel** [comment]
Hey @griffpatch, when you find the exact command to set this up on windows you should post it back here for other people to find.

**Comment by rschamp** [comment]
Yes and we will also update the wiki with that. And maybe put setup instructions directly into our `README` :)

**Comment by griffpatch** [comment]
Ok, I got further after installing closure ;) - But now I have a different
problem!

One of the errors is: Error: EMFILE: too many open files. But there are a
few others too.

See the log below:

$ npm install

> scratch-blocks@0.1.0 prepublish
C:\Users\Admin\Documents\GitHub\scratch-blocks
> python build.py && webpack

FAILED to create msg\js\constants.js
SUCCESS: msg\js\en.js
WARNING
Misplaced type annotation. Type annotations are not allowed here. Are you
missing parentheses?
core\blockly.js at line 32:
goog.provide('Blockly.Blocks');
^
()
SUCCESS: blockly_compressed_vertical.js
Size changed from 2914 KB to 726 KB (25%).
SUCCESS: blockly_uncompressed_horizontal.js
SUCCESS: blockly_uncompressed_vertical.js
WARNING
Misplaced type annotation. Type annotations are not allowed here. Are you
missing parentheses?
core\blockly.js at line 32:
goog.provide('Blockly.Blocks');
^
()
SUCCESS: blockly_compressed_horizontal.js
Size changed from 2896 KB to 719 KB (25%).
SUCCESS: blocks_compressed_horizontal.js
Size changed from 34 KB to 18 KB (53%).
SUCCESS: blocks_compressed_vertical.js
Size changed from 148 KB to 83 KB (56%).
SUCCESS: blocks_compressed.js
Size changed from 14 KB to 6 KB (43%).
SUCCESS: javascript_compressed.js
Size changed from 18 KB to 12 KB (67%).
SUCCESS: python_compressed.js
Size changed from 11 KB to 5 KB (49%).
SUCCESS: php_compressed.js
Size changed from 11 KB to 5 KB (50%).
SUCCESS: dart_compressed.js
Size changed from 9 KB to 4 KB (45%).
SUCCESS: lua_compressed.js
Size changed from 7 KB to 2 KB (42%).
Error: EMFILE: too many open files, open
'C:\Users\Admin\Documents\GitHub\scratch-blocks\gh-pages\closure-library\closure\goog\dom\classlist.js'
    at Error (native)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture:
fsevents@1.1.1
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-blocks@0.1.0 prepublish script 'python
build.py && webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scratch-blocks
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     python build.py && webpack
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs scratch-blocks
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scratch-blocks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Admin\Documents\GitHub\scratch-blocks\npm-debug.log

**Comment by rachel-fenichel** [comment]
Ignore this one:
```
WARNING
Misplaced type annotation. Type annotations are not allowed here. Are you
missing parentheses?
core\blockly.js at line 32:
goog.provide('Blockly.Blocks');
^
()
```
and this one:
```
WARNING
Misplaced type annotation. Type annotations are not allowed here. Are you
missing parentheses?
core\blockly.js at line 32:
goog.provide('Blockly.Blocks');
^
()
```
I think they're fixed in newer versions of scratch-blocks and blockly.

**Comment by griffpatch** [comment]
For the record, I was able to instal the closure library in windows using the instructions on the wiki `ln -s $(npm root)/google-closure-library ../closure-library` - whether this was because I ran it from the bash shell that comes with the  github client I'm not sure... But it worked.

However, I'm still unable to complete the `npm build` as I get the error:

```
Error: EMFILE: too many open files, open
'C:\Users\Admin\Documents\GitHub\scratch-blocks\gh-pages\closure-library\closure\goog\dom\classlist.js'
    at Error (native)
```

I've read lots of reports of this occurring with other npm projects and that the solution is to use a plugin (graceful-fs) that forces a limit on the number of files that can be opened at once?

Does nobody else get this issue? I guess most people are using macs? I am on windows 10.

**Comment by wattdave** [comment]
Or on Windows 10 I use an Ubuntu VM under Hyper-V.

**Comment by TheBrokenRail** [comment]
Here is a suggestion that might simplify the process for instalkling closoure, why don't you use a NPM plugin to create the symlink from ./node_moduoles/google-closure-library to ../google-closure automaticly when it runs prepublish?

**Comment by rschamp** [comment]
Hi @griffpatch do you continue to have issues with `npm run build` due to this `EMFILE` error?  @cwillisf Have you seen this before?

**Comment by Kenny2github** [comment]
Any further info on this?

**Comment by griffpatch** [comment]
Sorry, I've not had time to look at Scratch 3 for a while. I did get things
building, but I ran into issues with trying to build the blocks module.

**Comment by zhaozbcn** [comment]
I also met the problem ,this is what I have done, and it worked for me:
1）update nodejs 9.8;
2）install webpack in nodejs ；
3）copy google-closure-library  to scratch-blocks‘s parent directory and rename it to closure-library

**Comment by cwillisf** [comment]
scratch-blocks v2 is a complete rewrite built on top of upstream [Blockly](https://github.com/RaspberryPiFoundation/blockly/). The old build system (Google Closure compiler, `python build.py`, the `core/` and `shim/` directories, etc.) no longer exists. This issue is no longer applicable. Thank you for reporting it!

If you believe this issue is still relevant to scratch-blocks v2, please let us know and we can reopen it.
